// Agregador fino: database.js não tem mais lógica própria. Cada domínio vive
// em db/*.js (ver AGENTS.md) — este arquivo só requisita cada módulo e
// reexporta, por whitelist explícita, exatamente a mesma API pública que
// existia aqui antes da divisão (main.js/preload.js continuam fazendo
// require("./database") sem nenhuma mudança).
const conexao = require("./db/conexao");
const schema = require("./db/schema");
const produtos = require("./db/produtos");
const categorias = require("./db/categorias");
const clientes = require("./db/clientes");
const estoque = require("./db/estoque");
const precificacao = require("./db/precificacao");
const fornecedores = require("./db/fornecedores");
const financeiro = require("./db/financeiro");
const compras = require("./db/compras");
const vendas = require("./db/vendas");
const caixa = require("./db/caixa");
const relatorios = require("./db/relatorios");
const dashboard = require("./db/dashboard");
const sistema = require("./db/sistema");
const bancoAdmin = require("./db/banco-admin");
const usuarios = require("./db/usuarios");

module.exports = {
	db: conexao.getConexao,
	iniciarBanco: schema.iniciarBanco,
	getConexao: conexao.getConexao,
	desbloquearBanco: conexao.desbloquearBanco,
	trocarChave: conexao.trocarChave,
	isDesbloqueado: conexao.isDesbloqueado,
	bloquearBanco: conexao.bloquearBanco,
	listarTabelasBanco: bancoAdmin.listarTabelasBanco,
	resumoTabelasBanco: bancoAdmin.resumoTabelasBanco,
	consultarTabelaBanco: bancoAdmin.consultarTabelaBanco,
	exportarBancoJSON: bancoAdmin.exportarBancoJSON,
	verificarSenhaAdmin: bancoAdmin.verificarSenhaAdmin,
	hashSenhaUsuario: usuarios.hashSenhaUsuario,
	hashSenhaUsuarioLegado: usuarios.hashSenhaUsuarioLegado,
	verificarHashSenha: usuarios.verificarHashSenha,
	salvarProduto: produtos.salvarProduto,
	atualizarProduto: produtos.atualizarProduto,
	removerProduto: produtos.removerProduto,
	restaurarProduto: produtos.restaurarProduto,
	excluirProdutoPermanente: produtos.excluirProdutoPermanente,
	listProdutosDetalhados: produtos.listProdutosDetalhados,
	getProximoSkuProduto: produtos.getProximoSkuProduto,
	getProximoCodigoCategoria: categorias.getProximoCodigoCategoria,
	buscarSKU: produtos.buscarSKU,
	buscarProdutosPorTermo: produtos.buscarProdutosPorTermo,
	finalizarVenda: vendas.finalizarVenda,
	setDBPath: conexao.setDBPath,
	getDBPath: conexao.getDBPath,
	getProximoCodigoCliente: clientes.getProximoCodigoCliente,
	getDashboardStats: dashboard.getDashboardStats,
	getClientes: clientes.getClientes,
	salvarCliente: clientes.salvarCliente,
	atualizarCliente: clientes.atualizarCliente,
	removerCliente: clientes.removerCliente,
	restaurarCliente: clientes.restaurarCliente,
	excluirClientePermanente: clientes.excluirClientePermanente,
	buscarCliente: clientes.buscarCliente,
	getVendas: vendas.getVendas,
	getVendasHoje: vendas.getVendasHoje,
	importarVendasHistoricas: vendas.importarVendasHistoricas,
	getFaturamentoMedioHistorico: precificacao.getFaturamentoMedioHistorico,
	getItensVenda: vendas.getItensVenda,
	getMovimentacoesCliente: clientes.getMovimentacoesCliente,
	getEstoqueNegativo: estoque.getEstoqueNegativo,
	getCategorias: categorias.getCategorias,
	getListCategoriasWithUsage: categorias.getListCategoriasWithUsage,
	removerCategoria: categorias.removerCategoria,
	getPricingData: precificacao.getPricingData,
	getGlobalMargin: precificacao.getGlobalMargin,
	saveGlobalMargin: precificacao.saveGlobalMargin,
	getCustoFixoConfig: precificacao.getCustoFixoConfig,
	saveCustoFixoConfig: precificacao.saveCustoFixoConfig,
	saveAplicarCustoFixo: precificacao.saveAplicarCustoFixo,
	saveProductMargin: precificacao.saveProductMargin,
	saveProductPrice: precificacao.saveProductPrice,
	saveProductCost: precificacao.saveProductCost,
	saveProductTaxes: precificacao.saveProductTaxes,
	massUpdateMargem: precificacao.massUpdateMargem,
	salvarCategoria: categorias.salvarCategoria,
	salvarCategoriaComSubcategorias: categorias.salvarCategoriaComSubcategorias,
	exportBackup: sistema.exportBackup,
	importBackup: sistema.importBackup,
	backupAutomatico: sistema.backupAutomatico,
	registrarEntradaEstoque: estoque.registrarEntradaEstoque,
	getMovimentacoesEstoque: estoque.getMovimentacoesEstoque,
	getEstoqueBaixo: estoque.getEstoqueBaixo,
	getEstoqueVisaoGeral: estoque.getEstoqueVisaoGeral,
	salvarEstoqueMinimo: estoque.salvarEstoqueMinimo,
	ajustarEstoqueManual: estoque.ajustarEstoqueManual,
	converterOrcamento: vendas.converterOrcamento,
	getFornecedores: fornecedores.getFornecedores,
	salvarFornecedor: fornecedores.salvarFornecedor,
	atualizarFornecedor: fornecedores.atualizarFornecedor,
	removerFornecedor: fornecedores.removerFornecedor,
	listarProdutosFornecedor: fornecedores.listarProdutosFornecedor,
	salvarProdutoFornecedor: fornecedores.salvarProdutoFornecedor,
	removerProdutoFornecedor: fornecedores.removerProdutoFornecedor,
	getCustoFornecedorProduto: fornecedores.getCustoFornecedorProduto,
	criarPedidoCompra: compras.criarPedidoCompra,
	getPedidosCompra: compras.getPedidosCompra,
	getItensPedidoCompra: compras.getItensPedidoCompra,
	receberPedidoCompra: compras.receberPedidoCompra,
	cancelarPedidoCompra: compras.cancelarPedidoCompra,
	getLancamentos: financeiro.getLancamentos,
	criarLancamento: financeiro.criarLancamento,
	baixarLancamento: financeiro.baixarLancamento,
	excluirLancamento: financeiro.excluirLancamento,
	abrirCaixa: caixa.abrirCaixa,
	fecharCaixa: caixa.fecharCaixa,
	getCaixaAberto: caixa.getCaixaAberto,
	getResumoCaixaAberto: caixa.getResumoCaixaAberto,
	getHistoricoCaixa: caixa.getHistoricoCaixa,
	getFluxoCaixa: financeiro.getFluxoCaixa,
	getDRE: relatorios.getDRE,
	getRelatorioVendas: relatorios.getRelatorioVendas,
	getCurvaABC: relatorios.getCurvaABC,
	getComissoes: relatorios.getComissoes,
	registrarLog: bancoAdmin.registrarLog,
	getLogAtividades: bancoAdmin.getLogAtividades,
	autenticarUsuario: usuarios.autenticarUsuario,
	getUsuario: usuarios.getUsuario,
	listarUsuarios: usuarios.listarUsuarios,
	salvarUsuario: usuarios.salvarUsuario,
	removerUsuario: usuarios.removerUsuario,
	cancelarOrcamento: vendas.cancelarOrcamento,
	registrarDevolucao: vendas.registrarDevolucao,
	getDevolucoes: vendas.getDevolucoes,
	getItensDevolucao: vendas.getItensDevolucao,
	atualizarNotaFiscal: vendas.atualizarNotaFiscal,
	getCotacaoProduto: fornecedores.getCotacaoProduto,
	listarPrecosCliente: clientes.listarPrecosCliente,
	salvarPrecoCliente: clientes.salvarPrecoCliente,
	removerPrecoCliente: clientes.removerPrecoCliente,
	getPrecoCliente: clientes.getPrecoCliente,
	salvarImagemProduto: produtos.salvarImagemProduto,
	removerImagemProduto: produtos.removerImagemProduto,
	getCaminhoImagemProduto: produtos.getCaminhoImagemProduto,
	buscaGlobal: vendas.buscaGlobal,
};
